# Generated by Django 4.0.3 on 2022-06-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_accountvo_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountvo',
            old_name='irst_name',
            new_name='first_name',
        ),
    ]
