# Generated by Django 4.0.3 on 2022-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_rename_irst_name_accountvo_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
